### ISSUE TITLE
Criação de máquina virtual - Produção processo ETL

### ISSUE THREAD

**Issue by gabrielbdornas** [suges-mg/mapa-transformacao#106]
Já solicitado para Gestor da Intendência Henrique.

**Comment by gabrielbdornas** [comment]
@YanVieira1905, liberação para criação da máquina virtual feita no meu login. Pedido de ajuda a Henrique para configuração Hibernação da máquina.

![Image](https://github.com/automatiza-mg/mapa-transformacao/assets/49699290/7da527cc-f36f-4215-9f17-ed81d18d5144)

Essa opção pode deixar o processo mais barato, pois a máquina tem que funcionar uma ou duas horas por dia apenas (somente o tempo para buscar as informações atualizadas do Portal Mg e dar a carga no Portal de Dados abertos). Pela [documentação](https://learn.microsoft.com/en-us/azure/virtual-machines/hibernate-resume?tabs=osLimitsLinux%2CenablehiberPortal%2CcheckhiberPortal%2CenableWithPortal%2CcliLHE%2CUbuntu18HST%2CPortalDoHiber%2CPortalStatCheck%2CPortalStartHiber%2CPortalImageGallery#prerequisites-to-use-hibernation) da Microsoft, a hibernação tem que ser liberação na minha subscrição (por isso pedi ajuda de Henrique).

**Comment by YanVieira1905** [comment]
@gabrielbdornas, outras pessoas conseguem acessar a máquina pelo seu login?

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas, outras pessoas conseguem acessar a máquina pelo seu login?

@YanVieira1905, acredito que sim. Esta liberação é apenas para criação da máquina e não o uso. Podemos liberar acessos SSH, mas para testar preciso primeiro conseguir criá-la. Isso é muito parecido com o processo que utilizávamos na CGE e acredito que @Andrelamor vai se lembrar. Henrique já manifestou hoje e está olhando a configuração de [hibernação](https://github.com/automatiza-mg/mapa-transformacao/issues/106#issuecomment-2003868592).

**Comment by gabrielbdornas** [comment]
> [@YanVieira1905](https://github.com/YanVieira1905), liberação para criação da máquina virtual feita no meu login. Pedido de ajuda a Henrique para configuração Hibernação da máquina.

@dcd-github-admin, voltei a solicitar o auxílio do Henrique hoje, 08/04/2024, para criação de máquinas virtuais com a Hibernação. Isso será importante, principalmente, durante o período de testes.

**Comment by gabrielbdornas** [comment]
Após Henrique liberar criação de máquinas com Hibernação descobri que não são todos os tamanhos de máquinas permitidos:

![Image](https://github.com/automatiza-mg/mapa-transformacao/assets/49699290/8207ae1e-f3b0-409c-a92d-e3db83a55355)

[Esta parte da documentação](https://learn.microsoft.com/en-us/azure/virtual-machines/hibernate-resume?tabs=osLimitsLinux%2CenableWithPortal%2CcliLHE%2CUbuntu18HST%2CPortalDoHiber%2CPortalStatCheck%2CPortalStartHiber%2CPortalImageGallery) explica quais são possíveis. 

Pretendo criar uma máquina de 16GB de RAM, conforme figura acima, mas só depois que tivermos uma primeira versão da API sei para publicar. Penso que podemos utilizar esta máquina para vários processos como:

- Publicação base Portal Mg em formato aberto.
- API SEI.
- API resumo de textos (inteligência artificial).

Fecharei este Issue, pois entendo que já conseguimos criar as máquinas necessárias.
