### ISSUE TITLE
Criar nova macro para análise do Mapa

### ISSUE THREAD

**Issue by augustacora** [suges-mg/mapa-transformacao#108]
Neste issue, descrevo o processo de criação de uma nova macro voltada à análise do Mapa de transformação de serviços. 

No issue #107 , descrevi a construção de uma automatização no Automate para corrigir a macro errada. O robô conseguiu cumprir com a tarefa proposta, mas o tempo de execução longo em que trabalha fez com que a ideia de refazer a macro surgisse.

**Comment by YanVieira1905** [comment]
@augustacora, já chegou a tentar dar uma olhada no power query? Ele costuma ser uma boa alternativa para automatização de bases de dados.

**Comment by augustacora** [comment]
Não cheguei a olhar! Vou pesquisar mais sobre a ferramenta. Obrigada, Yan!

**Comment by augustacora** [comment]
Nos últimos dois meses, descobri que nossa macro só havia parado de funcionar porque a equipe da DCCD (que é quem nos fornece a planilha base para análise) havia parado de incluir no relatório as colunas "ID do órgão" e "ID do serviço". Ambas são parâmetros que a macro usa para identificar que as linhas são do mesmo serviço ou de serviços diferentes e, sem elas, a automatização não funcionava.
Pedi para o Bruno Notini voltar a incluir ambas as colunas nos relatórios mensais e o problema não mais ocorreu. Sendo assim, vou fechar este issue.
